Cu 86789du0k cd   ajustar repo deploy apps zendesk
eteg/deploy-app-zendesk pull request #11
Opened 2023-07-13 11:29 UTC by miacelPereira

O que foi feito:
 - Melhorias na pipeline de criação do app
 - Correção na parte de atualização do app

Dicas de como testar: 
  Temos o repositório https://github.com/eteg/mt-pipeline-deploy, que a branch develop já está configurada para receber essa action, então podemos excluir o app criado e mudar no zcli.apps.config.json o id para null e criar um novo app, após isso, podemos modificar o app colocando um texto diferente e fazendo o commit, para disparar a pipeline novamente mas dessa vez atualizando o app
 
 Link da task: https://app.clickup.com/t/86789du0k

2023-07-13 17:27 UTC, KayanHendges requested changes

2023-07-13 17:27 UTC, KayanHendges commented on index.ts
> -    const zendeskConfigPath = relativePath.normalize(`${path}/../zendesk.apps.config.json`);
Acho que foi mudado pra teste e esqueceram de mudar

2023-07-13 17:27 UTC, KayanHendges commented on package.json
> +    "jszip": "^3.10.1",
Essa lib não está sendo utilizada

```suggestion
    "axios": "^1.4.0"
```

2023-07-13 18:52 UTC, KayanHendges approved these changes

2023-07-17 12:04 UTC, FranciscoN3to approved these changes

2023-07-17 12:10 UTC, merged